<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tin Skoric">

<title>The Vibes from 2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<link rel="stylesheet" href="../../styles.css">
<script src="../../scripts.js" defer></script>
</head>

<body class="light-mode">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#sec-intro" id="toc-sec-intro" class="nav-link active" data-scroll-target="#sec-intro"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#measuring-sentiments" id="toc-measuring-sentiments" class="nav-link" data-scroll-target="#measuring-sentiments"><span class="header-section-number">2</span> Measuring Sentiments</a></li>
  <li><a href="#inflation-and-consumer-confidence" id="toc-inflation-and-consumer-confidence" class="nav-link" data-scroll-target="#inflation-and-consumer-confidence"><span class="header-section-number">3</span> Inflation and Consumer Confidence</a></li>
  <li><a href="#consumer-confidence-pre--and-post-pandemic" id="toc-consumer-confidence-pre--and-post-pandemic" class="nav-link" data-scroll-target="#consumer-confidence-pre--and-post-pandemic"><span class="header-section-number">4</span> Consumer Confidence Pre- and Post-Pandemic</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">5</span> Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">6</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
  <div>
    <div class="quarto-title">
    <h1 class="title" onclick="copyLink()">The Vibes from 2022</h1>
    </div>
    <div class="quarto-title-meta">
      <div><div class="quarto-title-meta-heading">Published</div><div class="quarto-title-meta-contents"><p class="date">September 2024</p></div></div>
    </div>
    <div>
      <div class="abstract">
        <div class="block-title"></div></div>
    </div>
    <br><br>
    </div>
    <div class="nav-bar">
      <div class="style-toggle"></div>
      <div class="nav-links">
        <a href="https://tins.page/">Home</a>
        <a href="https://tins.page//stuff/Resume.pdf"  target="_blank">Resume</a>
      </div>
  </div>
</header>

<section id="sec-intro" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Around this same time 2 years ago, I wrote a similarly short and (hopefully dissimilarly) crude post talking about the advent of “vibes based economics” as I’d seen it mentioned by other, more knowledgeable persons. The whole piece is rambling pontification, and I pray I’ve got better at these writings since then. I concluded it by talking about the need to maintain faith despite the malaise and that, “luckily,” spending hadn’t appeared to drop despite poor economic sentiment. In retrospect, this was not luck, but rather a feature of the new vibe. There is a growing disconnect between how people describe broader economic conditions, and how they operate under them. This disconnect is not an entirely new phenomenon, but it appears to have been particularly pronounced over these past four years. Consider the figure below from the Institute of Politics at Harvard Kennedy School (<span class="citation" data-cites="harvard"><span>“Harvard IOP Youth Poll”</span> (<a href="#ref-harvard" role="doc-biblioref">2023</a>)</span>):</p>
<div class="callout callout-style-simple callout-note no-icon" style="border-width: 5px;">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="fig-dipzone" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dipzone-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="https://iop.harvard.edu/youth-poll/46th-edition-fall-2023"><span class="lightbox" data-gallery="quarto-lightbox-gallery-1" data-glightbox="description: .lightbox-desc-1"><img src="TheVibes2022/survey.png" class="img-fluid figure-img"></span></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dipzone-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Harvard IOP Youth Poll; Fall 2023
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>If an economy is a system, and our personal economic health is a branch of it, then how could that branch be fine but the proverbial tree be dead? The gap in responses seen in <a href="#fig-dipzone" class="quarto-xref">Figure&nbsp;1</a> is non-negligible, and reflects an excessively pessimistic view of the macroeconomy among a large segment of the populace (in this case specifically, the 18-29 demographic). What this means for something like “sentometrics”<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> is difficult to ascertain—if we know that consumer sentiment impacts the economy, but we do not know what level of sentiments are reflective of ones that would create an impact, how do we know when the vibes have soured enough for something to change? I am not going to try to explain an answer to that here, but I do want to share a simple observation illustrating this problematic development.</p>
</section>
<section id="measuring-sentiments" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Measuring Sentiments</h1>
<p>To see how sentiment has changed compared to economic conditions, we need a measure of sentiment and a common economic indicator to compare. To keep things simple, I use consumer price index <span class="citation" data-cites="CPI">(<a href="#ref-CPI" role="doc-biblioref"><strong>CPI?</strong></a>)</span> inflation as the indicator of reference (PCE is better but CPI is what most mass media uses) and the consumer confidence index <span class="citation" data-cites="CCI">(<a href="#ref-CCI" role="doc-biblioref"><strong>CCI?</strong></a>)</span> to measure sentiment. I chose inflation because it is a metric that makes headlines, and which has some correlation with the sentiment metric when plotted. Don’t worry about stationarity econometricians, this is not about the number of inflation, it’s about the number of it that turns heads. I’ve elected to employ a one-month lag of inflation in comparing it to consumer sentiment since it would be the preceding month’s inflation that is known in the month of each consumer confidence survey. The time period of both datasets is January 2010 to June 2024<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Before proceeding, only one more thing is necessary.<br>
<br>
Although we are using CPI inflation data in this comparison, as mentioned in the above paragraph, we are looking for what makes headlines. This is to say that when inflation is on target, it is unlikely that it is a considerable factor in terms of consumer sentiment. Who was talking about inflation in December of the year 2020? In addition to simply grabbing inflation data, it is necessary to create a benchmark for the <em>kind of inflation</em> that makes headlines. To do this without going through the pain of actually aggregating news articles manually, I use Google Trends with the query “Inflation (Topic)” specifically concerning Google News searches <span class="citation" data-cites="google">(<a href="#ref-google" role="doc-biblioref"><span>“Inflation (Topic)”</span> 2024</a>)</span> over the same time frame as the CCI and CPI data. The results below illustrate Google News search interest in inflation over time:</p>
<div class="callout callout-style-simple callout-note no-icon" style="border-width: 5px;">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div>

</div>
<div class="quarto-layout-panel" data-layout-nrow="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-trends" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="TheVibes2022/figures/trends_plot.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" data-glightbox="description: .lightbox-desc-2"><img src="TheVibes2022/figures/trends_plot.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Google News Trends: Inflation (Topic),<br>
Data from Jan.&nbsp;2010 to Jun.&nbsp;2024, Vertical Lines Denote Mar.&nbsp;2020 and Jun.&nbsp;2022 Respectively
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p><a href="TheVibes2022/figures/trends_plot.png"><code>Download Plot</code></a></p>
</div>
</div>
</div>
</div>
</div>
</div>
<p>It is clear from <a href="#fig-trends" class="quarto-xref">Figure&nbsp;2</a> that during the interceding period of relative financial stability between the global financial crisis and the pandemic era, inflation was not really turning heads much. However, since interest is a relative measure, our perception of the data is surely skewed by the seismic nature of the pandemic. If we remove that period and consider only that from January 2010 to January 2020, things look very different:</p>
<div class="callout callout-style-simple callout-note no-icon" style="border-width: 5px;">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div>

</div>
<div class="quarto-layout-panel" data-layout-nrow="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-trends2020" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-trends2020-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="TheVibes2022/figures/trends_plot_2020.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" data-glightbox="description: .lightbox-desc-3"><img src="TheVibes2022/figures/trends_plot_2020.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-trends2020-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Google News Trends: Inflation (Topic),<br>
Data from Jan.&nbsp;2010 to Jan.&nbsp;2020
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p><a href="TheVibes2022/figures/trends_plot_2020.png"><code>Download Plot</code></a></p>
</div>
</div>
</div>
</div>
</div>
</div>
<p>What we want is to find a baseline level of inflation that correlates to “disinterest” during the period of stability. In other words, we want to find a general level for the interest trend in inflation as a topic, and see whereabouts inflation tends to be at that level. This level is not entirely representative of what constitutes inflation that makes headlines (for example, periods of particularly low inflation may do the same), but it makes it easier to make an interpretable graph so bear with me. As seen in the collapsed block below, the mean and median levels of interest across the period of interest are 13.55 and 6 respectively.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Google Trends Averages
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    5.00    6.00   13.55   14.00  100.00 </code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Given the difference between the first and third quartiles, and how close the mean is to the third, it appears the median is a better result to use here, so I continue with that. Now we adjust the data such that all cases where the trend of interest was above the median are marked as such, and from this we derive the average level of inflation given that interest is above trend<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Google Trends Averages: Inflation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
-0.02203  2.13811  3.16574  3.70907  5.05818  8.98974 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  95.91   98.07   99.10   99.64  100.99  104.92 </code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Inflation generally starts to turn heads when it hits about 3.168 to 3.71%. That sounds reasonable to my hind brain so we will continue. I elect to include both possible limits for the visual in the next section.</p>
</section>
<section id="inflation-and-consumer-confidence" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Inflation and Consumer Confidence</h1>
<p>Below is a graph of inflation and consumer confidence, covering a period from January 2010 to June 2024, with our baseline “head-turning” level of inflation from the prior section included:</p>
<div class="callout callout-style-simple callout-note no-icon" style="border-width: 5px;">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div>

</div>
<div class="quarto-layout-panel" data-layout-nrow="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-cci-all" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cci-all-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="TheVibes2022/figures/cc_plain_all.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" data-glightbox="description: .lightbox-desc-4"><img src="TheVibes2022/figures/cc_plain_all.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cci-all-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Inflation v. Consumer Confidence Index,<br>
Data from Jan.&nbsp;2010 to Jun.&nbsp;2024, Vertical Lines Denote Mar.&nbsp;2020 and Jun.&nbsp;2022 Respectively
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p><a href="TheVibes2022/figures/cc_plain_all.png"><code>Download Plot</code></a></p>
</div>
</div>
</div>
</div>
</div>
</div>
<p>As seen above in <a href="#fig-cci-all" class="quarto-xref">Figure&nbsp;4</a>, it is generally true that higher inflation in one month is reflected by a lower CCI in the next<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>, particularly during periods that exceeds the head-turning level. Running a simple test for correlation (in the collapsed block below) we get coefficients of about -0.630 or -0.699 that are statistically significant when including all CPI values or only those where the level of interest in inflation was above the median of 6 (the head-turning level roughly associated with an inflation rate of about 2.68%) respectively. In the years since 2010, we see that low inflation generally resulted in higher consumer confidence and vice versa, and we additionally see that when controlling to focus on inflation during periods where interest of it is higher (which is associated with the “head-turning number” at the higher end of inflation), that relationship is more pronounced.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Correlation Test: CPI v. CCI
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  consumer_confidence$CPI_lag and consumer_confidence$CCI
t = -10.649, df = 172, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.7123095 -0.5313987
sample estimates:
       cor 
-0.6303366 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  consumer_confidence_above_avg_interest$CPI_lag and consumer_confidence_above_avg_interest$CCI
t = -8.8062, df = 81, p-value = 1.92e-13
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.7951171 -0.5696011
sample estimates:
       cor 
-0.6993682 </code></pre>
</div>
</div>
</div>
</div>
</div>
<p>So we know it should be negative. Anecdotally, it is unlikely that we wouldn’t see a negative correlation between inflation and consumer confidence—not many are made confident by high inflation—so what could be different in different the era of the vibecession<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>? The size of the coefficients. To investigate if these differences exist, we split the data into pre- and post-vibecession groups.</p>
</section>
<section id="consumer-confidence-pre--and-post-pandemic" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Consumer Confidence Pre- and Post-Pandemic</h1>
<p>It’s fair to say the “vibecession” is a pandemic phenomenon, so it is worth looking at the years preceeding March 2020 to see how sentiments may have changed since. In the collapsed block below is another correlation text containing only values from January 2010 to February 2020.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Correlation Test: CPI v. CCI Pre-Pandemic
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  consumer_confidence_pre$CPI_lag and consumer_confidence_pre$CCI
t = -3.425, df = 121, p-value = 0.0008401
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.4506056 -0.1269328
sample estimates:
       cor 
-0.2972866 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  consumer_confidence_above_avg_interest_pre$CPI_lag and consumer_confidence_above_avg_interest_pre$CCI
t = -4.2829, df = 37, p-value = 0.0001258
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.7542238 -0.3179446
sample estimates:
       cor 
-0.5757083 </code></pre>
</div>
</div>
</div>
</div>
</div>
<p>The relationship of inflation and CCI noted from <a href="#fig-cci-all" class="quarto-xref">Figure&nbsp;4</a> is still present, but notably much-reduced. We get coefficients of about -0.297 or -0.576 that are statistically significant when including all CPI values or only those where the level of interest in inflation was above the median respectively. These are drastically lower than the original coefficients in both cases, implying that the pandemic (and recovery) period will have a much higher associated coefficient. Below is the same test but with values spanning only March 2020 to June 2024.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Correlation Test: CPI v. CCI Post-Pandemic
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  consumer_confidence_post$CPI_lag and consumer_confidence_post$CCI
t = -8.6315, df = 50, p-value = 1.783e-11
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.8640574 -0.6346413
sample estimates:
       cor 
-0.7735649 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  consumer_confidence_above_avg_interest_post$CPI_lag and consumer_confidence_above_avg_interest_post$CCI
t = -7.8226, df = 42, p-value = 9.915e-10
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.8684093 -0.6134182
sample estimates:
       cor 
-0.7700613 </code></pre>
</div>
</div>
</div>
</div>
</div>
<p>The relationship of inflation and CCI noted from <a href="#fig-cci-all" class="quarto-xref">Figure&nbsp;4</a> is still present, but is much higher. We get coefficients of about -0.774 or -0.770 that are statistically significant when including all CPI values or only those where the level of interest in inflation was above the median respectively. Interestingly, the coefficient is greater in magnitude in the latter case than the former, which is a reversal of what we saw in the prior two series of tests. Although almost all periods during the pandemic era had a level of interest above the median, this implies that even in cases where interest was not that high, inflation and consumer confidence were quite high and low respectively. This further illustrates the souring of the vibe during the pandemic and—given that those periods are found in 2020—probably reflect concerns about a recession<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> in those instances rather than inflation. The drop in CCI was much more pronounced across the 2022 inflationary wave than other waves in earlier years.</p>
</section>
<section id="conclusion" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Conclusion</h1>
<p>As seen in these quick tests, consumer confidence was more negatively impacted in respect to inflation in these past 4 years than it had been in the prior decade. Checking the CCI back to the 1970s, it reached a lower low in 2022 than in the decade of stagflation or the 2008 global financial crisis. Yet consumers still spent—aggregate consumption remained at trend throughout this period. Everything tells us that people were desperately concerned about the economy and yet they did not save and behave as people would historically. Again, the vibe soured, but not enough to significantly change behavior in terms of pure consumption long-term. Even when people weren’t focused on inflation and were pessimistic about a recession they still spent! Surely this isn’t an answer of spending by pure necessity either people bought other goods—look at the market for home office solutions and tell me it wasn’t huge. This begs the same question I asked earlier, how do we know when the vibes have soured enough for something to change?</p>
</section>
<section id="references" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-algaba2020" class="csl-entry" role="listitem">
Algaba, Andres, David Ardia, Keven Bluteau, Samuel Borms, and Kris Boudt. 2020. <span>“ECONOMETRICS MEETS SENTIMENT: AN OVERVIEW OF METHODOLOGY AND APPLICATIONS.”</span> <em>Journal of Economic Surveys</em> 34 (3): 512–47. <a href="https://doi.org/10.1111/joes.12370">https://doi.org/10.1111/joes.12370</a>.
</div>
<div id="ref-harvard" class="csl-entry" role="listitem">
<span>“Harvard IOP Youth Poll.”</span> 2023. <em>Institute of Politics at Harvard Kennedy School</em>. <a href="https://iop.harvard.edu/youth-poll/46th-edition-fall-2023">https://iop.harvard.edu/youth-poll/46th-edition-fall-2023</a>.
</div>
<div id="ref-google" class="csl-entry" role="listitem">
<span>“Inflation (Topic).”</span> 2024. <em>Google Trends</em>. <a href="https://trends.google.com/trends/explore?date=2010-01-01%202024-06-01&amp;geo=US&amp;gprop=news&amp;q=%2Fm%2F09jx2&amp;hl=en">https://trends.google.com/trends/explore?date=2010-01-01%202024-06-01&amp;geo=US&amp;gprop=news&amp;q=%2Fm%2F09jx2&amp;hl=en</a>.
</div>
<div id="ref-vibes" class="csl-entry" role="listitem">
Scanlon, Kyla. 2022. <span>“The Vibecession: The Self-Fulfilling Prophecy.”</span> <em>Kyla’s Newsletter</em>. <a href="https://kyla.substack.com/p/the-vibecession-the-self-fulfilling">https://kyla.substack.com/p/the-vibecession-the-self-fulfilling</a>.
</div>
</div>


<div class="hidden" aria-hidden="true">
<span class="glightbox-desc lightbox-desc-1">Figure&nbsp;1: Harvard IOP Youth Poll; Fall 2023</span>
<span class="glightbox-desc lightbox-desc-2">Figure&nbsp;2: Google News Trends: Inflation (Topic),<br>
Data from Jan.&nbsp;2010 to Jun.&nbsp;2024, Vertical Lines Denote Mar.&nbsp;2020 and Jun.&nbsp;2022 Respectively</span>
<span class="glightbox-desc lightbox-desc-3">Figure&nbsp;3: Google News Trends: Inflation (Topic),<br>
Data from Jan.&nbsp;2010 to Jan.&nbsp;2020</span>
<span class="glightbox-desc lightbox-desc-4">Figure&nbsp;4: Inflation v. Consumer Confidence Index,<br>
Data from Jan.&nbsp;2010 to Jun.&nbsp;2024, Vertical Lines Denote Mar.&nbsp;2020 and Jun.&nbsp;2022 Respectively</span>
</div>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Really cool field, (see: <span class="citation" data-cites="algaba2020">Algaba et al. (<a href="#ref-algaba2020" role="doc-biblioref">2020</a>)</span>).<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Using the lag of inflation for the same reasons discussed earlier.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Term coined by someone smarter than me: <span class="citation" data-cites="vibes">Scanlon (<a href="#ref-vibes" role="doc-biblioref">2022</a>)</span>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Using the lag of inflation for the same reasons discussed earlier.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Term coined by someone smarter than me: <span class="citation" data-cites="vibes">Scanlon (<a href="#ref-vibes" role="doc-biblioref">2022</a>)</span>.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>This aligns with Google Trends if you search for “Recession (Topic)” for March 2020 but I’m not about to make an entire extra graph for that.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"selector":".lightbox","openEffect":"zoom"});
window.onload = () => {
  lightboxQuarto.on('slide_before_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    const href = trigger.getAttribute('href');
    if (href !== null) {
      const imgEl = window.document.querySelector(`a[href="${href}"] img`);
      if (imgEl !== null) {
        const srcAttr = imgEl.getAttribute("src");
        if (srcAttr && srcAttr.startsWith("data:")) {
          slideConfig.href = srcAttr;
        }
      }
    } 
  });

  lightboxQuarto.on('slide_after_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    if (window.Quarto?.typesetMath) {
      window.Quarto.typesetMath(slideNode);
    }
  });

};
          </script>




</body></html>